In [1]:
import torch
import torch.nn as nn
import pprint


#lets define a simple model
class ConvNet(nn.Module):
   
    # Parameters:
    #           inputDepth: This is the number of channels of the input image -- usually 3 for RGB
    #           outputDepth: This is the number of channels coming out of the layer -- # of filters to apply
    #           kernel_size: width / height of the kernal (filter)
    
    def __init__(self, inputDepth, outputDepth, kernal_size=4):
        super(ConvNet, self).__init__()
        
        #A single convolutional layer
        self.conv1 = nn.Conv2d(inputDepth, outputDepth, kernel_size=4, stride=1, padding=0)
        
    def forward(self, x):
        out = self.conv1(x)
        return out

#I am going to define a function to make experimenting easier
def getInfo(inputDepth, outputDepth):
    model = ConvNet(inputDepth, outputDepth)
    sdict = model.state_dict()
    modelLayers = [(layer, param) for (layer, param) in sdict.items()]
    return modelLayers

model_layers = getInfo(1,1)


#lets take a look at what this looking like
print(model_layers[0][0])
print(model_layers[0][1])
print('\n') 
print(model_layers[1][0])
print(model_layers[1][1])

conv1.weight
tensor([[[[-0.0862, -0.1932, -0.2216, -0.0873],
          [-0.0502, -0.0715,  0.1485,  0.2203],
          [ 0.0616,  0.1377,  0.0253,  0.0593],
          [ 0.0039, -0.1559,  0.0376,  0.1531]]]])


conv1.bias
tensor([0.0109])


In [2]:
#This makes sense:

    # layer are stored in         model_layers[0]:
    #          layer name is in     model_layers[0][0]
    #          layer weights are in model_layers[0][1]

    # biases are store in the following layer in model_layers[1]:
    #                         layer name is      model_layers[1][0]
    #                         layer bias are in  model_layers[1][1]

#Explanation of the weights:
#These values are the values of the 4x4 filter or kernal

In [3]:




# Lets see what happens when we introduce 2 input channels ---- 
# ---- from now on I am only going to print weights and ignore biases
info = getInfo(2, 1)
pprint.pprint(info[0][1])
pprint.pprint(info[0][1].shape)

tensor([[[[-0.1244, -0.0269,  0.0086, -0.0200],
          [-0.1702, -0.0098,  0.0286, -0.0900],
          [-0.1577,  0.0061, -0.1146,  0.0653],
          [-0.1009,  0.0391, -0.1539, -0.0539]],

         [[ 0.1156,  0.0317,  0.1092, -0.0694],
          [ 0.1506,  0.0758, -0.1158,  0.1255],
          [-0.0117, -0.0984,  0.0354, -0.0052],
          [-0.1521, -0.1415, -0.0400,  0.1448]]]])
torch.Size([1, 2, 4, 4])


In [4]:
#we can now see there is a tensor of shape (1x2x4x4)
#in words (i believe) the structure of the 
#tensor is: (output filters)x(input filters)x(height of kernal)x(width of kernal)

In [5]:


# Lets see what happens when we introduce 2 output channels ---- 
info = getInfo(1, 2)
pprint.pprint(info[0][1])
pprint.pprint(info[0][1].shape)

tensor([[[[ 0.1596, -0.1478, -0.1207,  0.0268],
          [-0.0213,  0.1894, -0.1393,  0.1875],
          [ 0.0165, -0.2045, -0.2181,  0.1380],
          [ 0.1051,  0.2364,  0.0255,  0.1654]]],


        [[[ 0.1046, -0.0265,  0.1939,  0.1499],
          [ 0.2461, -0.0630,  0.1849, -0.1932],
          [-0.1160,  0.1278, -0.1098, -0.2062],
          [ 0.1843,  0.1696, -0.0857,  0.1495]]]])
torch.Size([2, 1, 4, 4])


In [6]:
#This is kind of expected ---- we can confirm the suspected tensor shape above


#lets make this a little more complex and use 2 input channels and 3 input channels
info = getInfo(2, 3)
pprint.pprint(info[0][1])
pprint.pprint(info[0][1].shape)

tensor([[[[ 0.1169,  0.1220,  0.0246, -0.0901],
          [-0.0622,  0.0527, -0.1185,  0.0847],
          [-0.0101, -0.1050,  0.0181, -0.0723],
          [-0.0224, -0.0524,  0.1022,  0.1713]],

         [[-0.0622, -0.1654, -0.0880, -0.1763],
          [-0.0905, -0.0722, -0.0542,  0.1662],
          [ 0.0811,  0.0021,  0.1104,  0.1484],
          [ 0.0629,  0.0738, -0.0793,  0.1689]]],


        [[[ 0.1294,  0.1267,  0.0191, -0.0226],
          [-0.0909, -0.1266, -0.0624, -0.0435],
          [ 0.0287, -0.0448,  0.1242,  0.1441],
          [ 0.0163, -0.0699, -0.1314, -0.1567]],

         [[-0.1717,  0.0111,  0.0503, -0.1684],
          [ 0.1632,  0.1122, -0.0684, -0.0699],
          [-0.1750,  0.0308, -0.0904,  0.0080],
          [ 0.1521,  0.0823, -0.0917, -0.0310]]],


        [[[ 0.0527,  0.0909,  0.0840, -0.1324],
          [ 0.1376,  0.0051, -0.0021, -0.0948],
          [-0.0714, -0.0714,  0.1006,  0.1119],
          [-0.0547, -0.0291,  0.0512, -0.1121]],

         [[ 0.1603,  0.109

In [7]:

#Lets look at 3 input channels and 2 output channels
info = getInfo(3, 2)
pprint.pprint(info[0][1])
pprint.pprint(info[0][1].shape)

tensor([[[[ 0.0098,  0.0462, -0.0066,  0.1044],
          [-0.0735,  0.0762,  0.0470,  0.0568],
          [-0.1078,  0.1034,  0.0961,  0.0129],
          [ 0.0859, -0.0339,  0.0137,  0.0295]],

         [[-0.0111, -0.0906, -0.0843,  0.0029],
          [-0.1166,  0.0847, -0.0159,  0.1203],
          [-0.0726,  0.0424, -0.0769,  0.1095],
          [-0.1405,  0.0398, -0.0763,  0.0761]],

         [[ 0.0522, -0.1293,  0.1252,  0.1438],
          [ 0.0320,  0.0665, -0.0361,  0.0286],
          [-0.1219, -0.0670,  0.0782,  0.0159],
          [-0.0659, -0.0394,  0.0817, -0.0587]]],


        [[[ 0.0994, -0.0189,  0.1107, -0.0459],
          [ 0.1318, -0.0587,  0.0436,  0.0503],
          [-0.1182,  0.0430,  0.0865, -0.0178],
          [ 0.0689, -0.0560, -0.0021, -0.1428]],

         [[-0.0263,  0.0476, -0.1092,  0.1204],
          [ 0.0241,  0.1000,  0.1041,  0.0506],
          [ 0.0044,  0.1185,  0.0891,  0.0244],
          [ 0.0505,  0.0958,  0.0677, -0.1348]],

         [[-0.0087,  0.0776,

In [16]:
#Great, with an understanding of how pytorch stores convolutional layers, lets try and iterate them
from torchvision import models

#I am going to redefine 'getInfo' function to collapse weights and biases for a layer together
def getInfo(inputDepth, outputDepth):
    #model = models.resnet101()
    model = ConvNet(inputDepth, outputDepth)
    sdict = model.state_dict()
    modelLayers = [(layer, param) for (layer, param) in sdict.items()]
    
    weights = []
    biases = []
    for _layer in modelLayers:
        if(not 'bn' in _layer[0] and not 'downsample' in _layer[0]):
            if('weight' in _layer[0]):
                weights.append((_layer[0][:-len('weight')], _layer[1]))
            elif('bias' in _layer[0]):
                biases.append((_layer[0][:-len('bias')], _layer[1]))
  
    cleanedLayers = []
    for weight_name, weight in weights:
        weight_nameFound = False
        for bias_name, bias in biases:
            if weight_name == bias_name:
                cleanedLayers.append([weight_name, weight, bias])
                weight_nameFound = True
                break
        if not weight_nameFound:
            cleanedLayers.append([weight_name, weight, []])
        
    return cleanedLayers

cleanedLayers = getInfo(3,2)
print((cleanedLayers))


[['conv1.', tensor([[[[ 0.0769, -0.0626, -0.0122, -0.0983],
          [ 0.0488, -0.0306, -0.1050,  0.0276],
          [ 0.0002,  0.1308,  0.0671,  0.1290],
          [-0.0197,  0.1180, -0.0473,  0.0657]],

         [[-0.0351, -0.0693,  0.1381, -0.0443],
          [-0.0552, -0.0465, -0.0321,  0.0303],
          [-0.0442, -0.1316,  0.0825,  0.1271],
          [ 0.0985,  0.0699, -0.1259, -0.0003]],

         [[ 0.0879, -0.0755,  0.1434, -0.0040],
          [-0.1317, -0.0571, -0.0891, -0.1174],
          [-0.0706, -0.0465, -0.0312,  0.1152],
          [ 0.0118,  0.0015, -0.0644, -0.1250]]],


        [[[ 0.0152, -0.0762,  0.0291,  0.0095],
          [-0.0671,  0.0046, -0.0532, -0.0332],
          [ 0.0426,  0.0453,  0.1406, -0.0818],
          [-0.1021,  0.0786,  0.0267,  0.1312]],

         [[ 0.1269,  0.0045,  0.1097, -0.1147],
          [-0.1237, -0.1180, -0.0130, -0.0329],
          [-0.0679, -0.1095, -0.0674,  0.1315],
          [ 0.0558, -0.0090,  0.1173, -0.0903]],

         [[-0.04

In [28]:
#As we can see getInfo will now return a cleaned up version of the layers,weights, and biases
#each index of 'cleanedLayers' is a particular layer
#at each index 'i', 
#      cleanedLayers[i][0] is layer name, 
#      cleanedLayers[i][1] is weights, 
#      and cleanedLayers[i][2] is biases

layers = getInfo(3,2)
print(layers)

[['conv1.', tensor([[[[ 0.0514, -0.0300,  0.1021,  0.0090],
          [-0.0535, -0.0181,  0.1166,  0.0969],
          [-0.0288,  0.1353, -0.1340,  0.0002],
          [ 0.0204,  0.0157,  0.0382,  0.0522]],

         [[-0.1092, -0.0651,  0.0431, -0.0978],
          [ 0.1304, -0.0445, -0.1115, -0.1316],
          [ 0.0345,  0.1440, -0.0561, -0.1073],
          [ 0.0772,  0.1240,  0.0377, -0.0599]],

         [[ 0.0144,  0.1376, -0.0683,  0.1398],
          [ 0.0178,  0.0206, -0.0785,  0.0086],
          [ 0.1176, -0.0856,  0.0651,  0.0674],
          [ 0.1386,  0.0525, -0.0703,  0.0331]]],


        [[[ 0.0926,  0.0537, -0.0306,  0.0959],
          [ 0.0715, -0.0706, -0.0889, -0.0026],
          [ 0.0720,  0.1013,  0.0181, -0.0535],
          [ 0.0863,  0.1197, -0.0164, -0.1183]],

         [[-0.0538, -0.0975,  0.0009,  0.1262],
          [-0.1302,  0.0982, -0.0826, -0.0941],
          [-0.1424,  0.1057, -0.0029, -0.0083],
          [ 0.0988, -0.1165,  0.0983, -0.0516]],

         [[-0.12