In [1]:
import torch
import torch.nn as nn
from getModelLayers import getModelLayers
from zeroNeurons import zeroListOfWeightIndexes
import pprint

############################################################################################################
# Parameters:
#           inputDepth: This is the number of channels of the input image -- usually 3 for RGB
#           outputDepth: This is the number of channels coming out of the layer -- # of filters to apply
#           kernel_size: width / height of the kernal (filter)
class ConvNet(nn.Module):   
    def __init__(self, inputDepth, outputDepth, kernal_size=3):
        super(ConvNet, self).__init__()
        
        #A single convolutional layer
        self.conv1 = nn.Conv2d(inputDepth, outputDepth, kernel_size=kernal_size, stride=1, padding=0)
        self.conv2 = nn.Conv2d(outputDepth, 3, kernel_size=kernal_size, stride=1, padding=0)
        self.fc1 = nn.Linear(3, 5)
    
    def forward(self, x):
        out = self.conv1(x)
        out = self.conv2(out)
        out = self.fc1(out)
        return out

In [2]:
#build simple net for example
net = ConvNet(2, 3)

In [3]:
#get model layers from the net -- explanation of getModelLayers shown in jupyter notebook
modelLayers = getModelLayers(net)

In [4]:
#loop through modelLayers and print weights before zeroing neurons
for layer_name, weights, biases in modelLayers:
    pprint.pprint(layer_name)
    pprint.pprint(weights)

'fc1.'
tensor([[-0.5522, -0.3248,  0.1447],
        [ 0.2017,  0.0661, -0.3483],
        [-0.1660,  0.0606,  0.3380],
        [ 0.5736, -0.1824,  0.4224],
        [-0.1412, -0.5712, -0.1911]])
'conv2.'
tensor([[[[-0.1613, -0.0912,  0.0568],
          [ 0.1875, -0.1284,  0.1628],
          [ 0.1406, -0.1037,  0.0729]],

         [[ 0.1510,  0.0179, -0.0548],
          [-0.0503, -0.0779, -0.1292],
          [-0.0725,  0.0058, -0.1517]],

         [[-0.1593,  0.0143, -0.0801],
          [-0.0144, -0.1530, -0.1447],
          [-0.0913,  0.0140, -0.0764]]],


        [[[-0.0352, -0.0274, -0.1108],
          [ 0.0993, -0.1346,  0.1734],
          [-0.0105,  0.1530,  0.1665]],

         [[-0.1791,  0.1594,  0.0644],
          [ 0.0486, -0.1635,  0.1454],
          [ 0.1143,  0.0958,  0.0778]],

         [[-0.0654, -0.0253, -0.0236],
          [ 0.1025,  0.1532, -0.0681],
          [ 0.0745,  0.0357,  0.0426]]],


        [[[-0.0816, -0.0762,  0.0012],
          [ 0.1578, -0.1695, -0.1627],
  

In [5]:
#example list format for input to zeroListOfWeightIndexes
list_of_weight_indexes =[
                            #at index [0][1] (the weights at layer 0) of modelLayers, zero neurons at index 0,1,4
                            [0, 1, [0, 1, 4]], 
                            #at index [1][1] of modelLayers, zero neurons at index 2
                            [1, 1, [2]],
                            #at index [2][1] of modelLayers, zero neurons at index 0
                            [2, 1, [0]]
                        ]

#zero neurons
zeroListOfWeightIndexes(list_of_weight_indexes, modelLayers)

#loop through the updated modelLayers
for layer_name, weights, biases in modelLayers:
    pprint.pprint(layer_name)
    pprint.pprint(weights)
        

'fc1.'
tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [-0.1660,  0.0606,  0.3380],
        [ 0.5736, -0.1824,  0.4224],
        [ 0.0000,  0.0000,  0.0000]])
'conv2.'
tensor([[[[-0.1613, -0.0912,  0.0568],
          [ 0.1875, -0.1284,  0.1628],
          [ 0.1406, -0.1037,  0.0729]],

         [[ 0.1510,  0.0179, -0.0548],
          [-0.0503, -0.0779, -0.1292],
          [-0.0725,  0.0058, -0.1517]],

         [[-0.1593,  0.0143, -0.0801],
          [-0.0144, -0.1530, -0.1447],
          [-0.0913,  0.0140, -0.0764]]],


        [[[-0.0352, -0.0274, -0.1108],
          [ 0.0993, -0.1346,  0.1734],
          [-0.0105,  0.1530,  0.1665]],

         [[-0.1791,  0.1594,  0.0644],
          [ 0.0486, -0.1635,  0.1454],
          [ 0.1143,  0.0958,  0.0778]],

         [[-0.0654, -0.0253, -0.0236],
          [ 0.1025,  0.1532, -0.0681],
          [ 0.0745,  0.0357,  0.0426]]],


        [[[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
  

In [6]:
#as shown above the neurons have been correctly zeroed